<a href="https://colab.research.google.com/github/justinpatel/FrozenLake-QLearning/blob/master/Reinforcement_Learning_with_Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gym
import numpy as np
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [9]:
print(env.observation_space.n) #no of states
print(env.action_space.n)      #no of actions

16
4


In [25]:
action = env.action_space.sample()
action

3

In [14]:
env.reset()

0

In [26]:
new_state, reward, done, info = env.step(action)

In [3]:
env.reset()

0

In [4]:
env.render()
# S is starting position
# F is Frozen lake
# H is hole
# G is goal


SFFF
FHFH
FFFH
HFFG


In [5]:
STATES = env.observation_space.n
ACTIONS = env.action_space.n

Q = np.zeros((STATES, ACTIONS))

In [9]:
EPISODES = 2000  #no of times run the environment from beginning
MAX_STEPS = 100  #no of max steps allowed for each run of environment 

LEARNING_RATE = 0.8
GAMMA = 0.96

RENDER = False

epsilon = 0.9  #90% chance of taking random sample of action

Q[state, action] = Q[state, action] + learning_rate * (reward + GAMMA * np.max(Q[new_state, :]) - Q[state, action])

In [11]:
rewards = []

for episode in range(EPISODES):
  state = env.reset()

  for _ in range(MAX_STEPS):
    clear_output(wait=True)
    if RENDER:
      env.render()
      time.sleep(0.3)

    if np.random.uniform(0,1) < epsilon:
      action = env.action_space.sample()
    else:
      action = np.argmax(Q[state, :])

    next_state, reward, done, _ = env.step(action)

    Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA * np.max(Q[next_state, :]) - Q[state, action])

    state = next_state

    if done:
      rewards.append(reward)
      epsilon -= 0.001
      break

In [12]:
print(Q)

[[1.22527717e-01 5.92099418e-03 6.40658173e-03 6.26125954e-03]
 [1.23726325e-03 1.39236640e-03 1.12883471e-03 2.05140462e-01]
 [3.21733684e-03 4.59810802e-03 2.54554209e-03 4.75811704e-01]
 [1.47893547e-03 9.48134697e-04 1.03279523e-03 5.96673618e-02]
 [1.62469091e-01 1.51632213e-03 1.71408162e-03 2.29740096e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.75099959e-01 8.14763919e-06 1.04108595e-05 5.79425724e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.23302123e-03 2.95769876e-03 1.24084961e-03 3.95453569e-01]
 [8.95304664e-04 1.74755253e-01 3.84995038e-03 1.11682863e-03]
 [7.97734687e-01 1.11448457e-03 6.22052737e-04 6.12841671e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.96620919e-02 3.26332555e-02 7.75283147e-01 2.83249577e-02]
 [1.85563899e-01 9.98543673e-01 1.92245790e-01 1.11596075e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [13]:
print(np.average(rewards))

0.406
